theme = "Materia"
enabled = true
battery_low_percent = 15
battery_critical_percent = 5
startup_sound = "soundthemed-start"
shutdown_sound = "soundthemed-stop"

[events]
power-unplug = "none"
alarm-clock-elapsed = "alarm-clock-elapsed"
power-plug = "none"

[sources]
udev = true
battery = true
network = true
session = true
volume = true
notifications = true
dbus_service = true
