theme = "freedesktop"
enabled = true
battery_low_percent = 15
battery_critical_percent = 5
startup_sound = "none"
shutdown_sound = "none"

[events]
power-unplug = "none"
power-plug = "none"

[sources]
udev = false
battery = true
network = false
session = false
volume = false
notifications = true
dbus_service = true
