INBOX     = folder:fastmail/Inbox
Archive   = folder:fastmail/Archive
Drafts    = folder:fastmail/Drafts
Scheduled = folder:fastmail/Scheduled
Sent      = folder:fastmail/Sent
Spam      = folder:fastmail/Spam
Trash     = folder:fastmail/Trash
Unread    = tag:unread
Outbox    = folder:fastmail/Outbox
Failed    = folder:fastmail/Failed
